(function() {var implementors = {};
implementors["coaster_nn"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"enum\" href=\"coaster_nn/enum.ConvForwardAlgo.html\" title=\"enum coaster_nn::ConvForwardAlgo\">ConvForwardAlgo</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"enum\" href=\"coaster_nn/enum.ConvBackwardFilterAlgo.html\" title=\"enum coaster_nn::ConvBackwardFilterAlgo\">ConvBackwardFilterAlgo</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"enum\" href=\"coaster_nn/enum.ConvBackwardDataAlgo.html\" title=\"enum coaster_nn::ConvBackwardDataAlgo\">ConvBackwardDataAlgo</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"struct\" href=\"coaster_nn/frameworks/native/helper/struct.NormalizationConfig.html\" title=\"struct coaster_nn::frameworks::native::helper::NormalizationConfig\">NormalizationConfig</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"struct\" href=\"coaster_nn/frameworks/native/helper/struct.PoolingConfig.html\" title=\"struct coaster_nn::frameworks::native::helper::PoolingConfig\">PoolingConfig</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"struct\" href=\"coaster_nn/frameworks/native/helper/struct.DropoutConfig.html\" title=\"struct coaster_nn::frameworks::native::helper::DropoutConfig\">DropoutConfig</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"struct\" href=\"coaster_nn/frameworks/native/helper/struct.ConvolutionConfig.html\" title=\"struct coaster_nn::frameworks::native::helper::ConvolutionConfig\">ConvolutionConfig</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
